### ISSUE TITLE
New crash new SDK an issue maybe?

### ISSUE THREAD

**Issue by KennyGoers** [danoz73/RecyclerViewFastScroller#21]
I updated to the latest recyclerview and sdk and started getting the error below, but downloaded the code and seem to be getting the same error from the sample, not sure what the cause is except that there seems to be an issue with a scroll event being initiated before the "calculator" is created by the onLayout(), I made a hack to fix it by checking if it had been created before calling it and everything works fine. 

03-15 21:12:59.157    3304-3304/xyz.danoz.recyclerviewfastscroller.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: xyz.danoz.recyclerviewfastscroller.sample, PID: 3304
    java.lang.NullPointerException: Attempt to invoke interface method 'float xyz.danoz.recyclerviewfastscroller.calculation.progress.TouchableScrollProgressCalculator.calculateScrollProgress(android.support.v7.widget.RecyclerView)' on a null object reference
            at xyz.danoz.recyclerviewfastscroller.AbsRecyclerViewFastScroller$1.onScrolled(AbsRecyclerViewFastScroller.java:185)
            at android.support.v7.widget.RecyclerView.notifyOnScrolled(RecyclerView.java:3248)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2229)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)

**Comment by Maxr1998** [comment]
Yes, seems SDK is causing issues.. I get this: java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.danoz.recyclerviewfastscroller.vertical.VerticalRecyclerViewFastScroller.setRecyclerView(android.support.v7.widget.RecyclerView)' on a null object reference

**Comment by danoz73** [comment]
8fdde1a1386487ee3625843b7b09555868287bd8
