### ISSUE TITLE
Crash on recycleview

### ISSUE THREAD

**Issue by SaurabhGaddelpalliwar** [danoz73/RecyclerViewFastScroller#76]
when i using same xml in another Activity
i m using 'xyz.danoz:recyclerviewfastscroller:0.1.3' 

java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.recyclerview.widget.RecyclerView$LayoutManager androidx.recyclerview.widget.RecyclerView.getLayoutManager()' on a null object reference
        at xyz.danoz.recyclerviewfastscroller.calculation.progress.VerticalLinearLayoutManagerScrollProgressCalculator.calculateScrollProgress(VerticalLinearLayoutManagerScrollProgressCalculator.java:25)
        at xyz.danoz.recyclerviewfastscroller.AbsRecyclerViewFastScroller.onLayout(AbsRecyclerViewFastScroller.java:206)

**Comment by SaurabhGaddelpalliwar** [comment]
please fix this issue

**Comment by masif040** [comment]
i have also this issue can it solve
